name: Deploy to FiveM Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync files to hosting
        uses: ftp-deploy/ftp-deploy-action@v1
        with:
          server: root.atlasnetwork.uk
          username: archie
          password: ${{ secrets.ftp_password }}
          local-dir: ./
          server-dir: ./
